# Generated by Django 5.1.15 on 2026-08-18 14:00

import apps.whiteboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(default=apps.whiteboard.models.generate_code, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
