# Generated by Django 5.1.15 on 2026-08-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0002_alter_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='active_file_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='mode',
            field=models.CharField(choices=[('SCAFFOLD', 'Scaffold'), ('EDIT', 'Edit'), ('EXPLAIN', 'Explain')], default='SCAFFOLD', max_length=50),
        ),
    ]
