# Generated by Django 5.1.15 on 2026-08-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0003_generationjob_active_file_path_generationjob_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='invite_code',
        ),
    ]
